version: '{branch}-{build}'

branches:
  only:
    - master

skip_tags: true
max_jobs: 1
image: Visual Studio 2015
clone_folder: C:\projects\downfall
clone_depth: 1

install:
  - cd C:\projects\downfall\sp\src
  - devtools\bin\vpc.exe /downfall +game +shaders /mksln game.sln
  - copy game.sln+sln_fix.txt game.sln

configuration: Release

build:
  parallel: true
  project: sp\src\game.sln

  verbosity: minimal

test: off  
  
after_build:
  - if exist C:\projects\downfall\sp\game\downfall\bin\*.pdb del /f C:\projects\downfall\sp\game\downfall\bin\*.pdb
  - set APPVEYOR_REPO_COMMIT=%APPVEYOR_REPO_COMMIT:~0,7%

artifacts:
  - path: sp\game\downfall\bin
    name: game_bin_$(APPVEYOR_REPO_COMMIT)
    type: zip